blank_issues_enabled: false
contact_links:
  - name: Install Extension
    url: https://dub.sh/getcomet?utm_source=github_getcomet-support_issue-template
    about: Install extension from Chrome Web Store
  - name: LinkedIn
    url: https://linkedin.com/in/anjantalatam
    about: Connect with the developer on LinkedIn
  - name: Twitter
    url: https://twitter.com/anjantalatam
    about: Follow for Updates